version: '2.27'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8181:8181"  # Remplacez par le port exposé par votre API

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Remplacez par le port exposé par votre application frontale
    depends_on:
      - api